### ISSUE TITLE
Debug support in vscode

### ISSUE THREAD

**Issue by goldytech** [hardikkaji/angularjs-es6-starter-kit#1]
Hi,

I tried to specified in webpack.config.js `devtool:'source-map',` but still i m unable to debug in vscode or chrome debugging tools in browser.

Also would it be possible to extend the kit of showcasing angularjs services with `$http`
and injecting this service in the controller 

Thanks

**Comment by hardikkaji** [comment]
@goldytech -- i have not tried it with vscode debugger. I need to check with that. Let me do that. I'll get back to you soon. if you have fix for this then feel free to open PR for it.

**Comment by goldytech** [comment]
Thanks for your response. VS Code debug can be optional, atleast it would be good if we can get debug going in Chrome browser. The problem here is the source map files are not getting generated even specifying it in  webpackconfig.js. (`devtool:'source-map'`) This is my first time with webpack, Till now I had utilized gulp.

Please help.

**Comment by hardikkaji** [comment]
@goldytech  - i have fixed source map generation issue you can see now source maps in chrome and debug code inside chrome. I am still working on debug with VS Code.

**Comment by hardikkaji** [comment]
@goldytech - you need to add below configuration in `launch.json` file.

```
{
   "type":"node",
   "request":"launch",
   "name":"Debug",
   "program":"${workspaceFolder}/node_modules/webpack-dev-server/bin/webpack-dev-server",
   "args":[
      "--progress",
      "--debug"
   ]
},
{
   "name":"Launch Chrome against localhost, with sourcemaps",
   "type":"chrome",
   "request":"launch",
   "url":"http://localhost:3000",
   "sourceMaps":true,
   "webRoot":"${workspaceRoot}"
}
```

**Comment by hardikkaji** [comment]
@goldytech - As you have asked for Example for `$http` -- i have also added same in project.

Check this [commit](https://github.com/hardikkaji/angularjs-es6-starter-kit/commit/7f92a2e1ad62b1f1992c686f4a073c3bfa893926).

**Comment by goldytech** [comment]
Thank you so much. You are awesome :)
